### ISSUE TITLE
[Bug]: Exterior overlay not updating on summon

### ISSUE THREAD

**Issue by Mansarde** [amblelabs/ait#1066]
### What happened?

Summoning the TARDIS (via the sonic) from an unloaded chunk when it has a biome overlay will not update the overlay texture after its arrival until the player enters the TARDIS or reloads the map.

1. Get a sonic, linked to the TARDIS.
2. Choose a police box exterior.
3. Transport the TARDIS to a biome that gives it an overlay texture (e.g. a snowy biome).
4. Go outside and make sure the exterior has an overlay texture.
5. Teleport the player (i.e. without the TARDIS) to a non-overlay biome far away from the TARDIS (so that it's in an unloaded chunk).
6. Now with the sonic in `TARDIS` mode, summon the TARDIS.
7. Once it arrives the exterior will still have the overlay texture from the biome it was summoned from, which will update once the player enters the TARDIS or reloads the map.

### Version

1.2.0

### Build number & branch

2242

### Logs & screenshots

![Image](https://github.com/user-attachments/assets/1d021efb-1997-43bb-a937-2926fddc77e4)

### I've checked the reported issues...

- [x] ...and this issue was not reported before.

**Comment by DrTheodor** [comment]
i guess this should apply to every biome overlay

**Comment by DrTheodor** [comment]
@Saturnorsomthing please triage this

**Comment by Loqor** [comment]
Fixed

**Comment by Mansarde** [comment]
It doesn't seem to be fixed, I can still reproduce it in 1.2.0.36:
![Image](https://github.com/user-attachments/assets/5787612d-c103-4581-9e46-27a43ef74ad8)

To be sure:
It only happens when you summon the TARDIS from an unloaded chunk.

**Comment by Mansarde** [comment]
Oh, and I used the "DEFAULT" police box.
Just mentioning this because I noticed some police boxes don't have a biome overlay (e.g. the war police box).

**Comment by duzos** [comment]
reproduced

**Comment by duzos** [comment]
![Image](https://github.com/user-attachments/assets/820120be-024c-41a9-8673-19b1e4522048)

**Comment by duzos** [comment]
definitely is
server sets it back to `DEFAULT` but client isnt synced

**Comment by DrTheodor** [comment]
Oh thats weird
why wont it sync?
