### ISSUE TITLE
Not freezing in Siege Mode

### ISSUE THREAD

**Issue by Mansarde** [amblelabs/ait#1323]
### What happened?

**<ins>Description:</ins>**
During siege mode the player doesn't have the freeze effect applied to them.

**<ins>Expectation:</ins>**
After a minute (60 x 20 ticks) in siege mode and with life support disabled, the player should have a freeze effect applied to them.

</BR>

**<ins>Steps to reproduce the behavior:</ins>**
1. Wear nothing but a respirator.
2. Disable life support.
3. Engage siege mode.
4. Wait at least 60 seconds and notice that no freezing happens to the player.

<hr>

For a quick code orientation, this is where it's determined when the player should have freezing applied to them: https://github.com/amblelabs/ait/blob/b326c0160a4028d5735df0000d1e493e01778077/src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java#L164-L165

### Version

1.2.0

### Build number & branch

release 2788 and beta 363

### Logs & screenshots

N/A

### I've checked the reported issues...

- [x] ...and this issue was not reported before.

**Comment by DrTheodor** [comment]
haha thats my fault
its most likely applying the tick freezes but they go away very quickly :P
siege ticks each half a second because of my changes so

**Comment by Mansarde** [comment]
Would it work again if we'd just increase the frozen ticks that get applied to the player, so that they stay longer? 🤔

**Comment by DrTheodor** [comment]
nah i just gotta update the code to add more freezing ticks

**Comment by Mansarde** [comment]
I'm still not freezing after more than 3 minutes in siege mode without life support and only wearing a respirator.
And when I take off the respirator I only get the usual "Weakness II" debuff, no freezing effect though.

Tested a few minutes ago on beta `415`.

**Comment by Mansarde** [comment]
> its impossible for it to not work

Have you tested it yourself?

**Comment by Loqor** [comment]
I fixed it, basically there was no initial freeze value so it never added anything

**Comment by Mansarde** [comment]
I do get the frozen corners now and the hearts are frozen over.
But unfortunately I still don't get any debuff that actually damages me. (As of beta build `425`)

I don't know if this is important, but it looks like the hearts flicker between the normal red hearts and the frozen hearts.
Could it perhaps be that the freezing-ticks are too short to apply any damage?
@DrTheodor mentioned something about that before.

Here's a short clip that shows this heart flickering:

https://github.com/user-attachments/assets/13ab38a1-c2c4-4928-97c8-36680328849d

**Comment by Mansarde** [comment]
# Siege mode still not freezing the player

The check to determine whether the freeze effect should be applied is here:
https://github.com/amblelabs/ait/blob/f9d4b514fb3cb7c70a350ecdc901e5adf620fa4c/src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java#L157-L158

Unfortunately, `isSiegeBeingHeld()` will always return true, regardless if the siege cube is held or not, leading to the freeze effect never being applied.

The reason that this method always returns true is because the way that the method checks whether a player is holding the siege cube is by checking `heldKey` against null:
https://github.com/amblelabs/ait/blob/f9d4b514fb3cb7c70a350ecdc901e5adf620fa4c/src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java#L94-L96

But `heldKey` will always be a non-null value.

### Explanation:
`heldKey` is initialized here via `HELD_KEY.create()`:
https://github.com/amblelabs/ait/blob/f9d4b514fb3cb7c70a350ecdc901e5adf620fa4c/src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java#L48

`HELD_KEY` itself is initialized with a new UUID full of zeroes:
https://github.com/amblelabs/ait/blob/f9d4b514fb3cb7c70a350ecdc901e5adf620fa4c/src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java#L43

Meaning if no player is holding the siege cube, the value of `heldKey` won't be _null_, but rather a UUID with all zeroes.

### Potential solution:
So instead of having `isSiegeBeingHeld()` check `heldKey` against null, it should rather check against the zero-UUID: `!heldKey.get().equals(UUID.fromString("00000000-0000-0000-0000-000000000000"))`.
Doing that makes the freeze effect work again, although without dealing damage still.

(Perhaps an Optional could be used, not sure how much overhead that would be though.)
