### ISSUE TITLE
register categories twice?

### ISSUE THREAD

**Issue by OwOday** [amblelabs/ait#214]
**Describe the bug**
I've got 
java.lang.IllegalStateException: Tried to register resource reloader ait:categories twice!

**AIT Version:**
1.2.46-1.20.1-beta

**Additional context**
I ran into this working on a pack with hundreds of mods, so its possible it's hard to reproduce.

**Comment by OwOday** [comment]
feel free to close as not planned if this bug doesn't make any sense

**Comment by Duzos** [comment]
Did this cause a crash?

**Comment by Loqor** [comment]
Fixed in release update.

**Comment by Eyerisss** [comment]
Still present in Quilt

```

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ait'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Tried to register resource reloader ait:categories twice!
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.registerReloader(ResourceLoaderImpl.java:160)
	at net.fabricmc.fabric.impl.resource.loader.ResourceManagerHelperImpl.registerReloadListener(ResourceManagerHelperImpl.java:50)
	at mdteam.ait.registry.CategoryRegistry.init(CategoryRegistry.java:103)
	at mdteam.ait.AITMod.onInitialize(AITMod.java:82)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more
```

in release 1.0.1, similarly have a lot of mods.

Tested in fabric, unique to quilt.

**Comment by Duzos** [comment]
odd
this issue was just ignored as it was a warning not a crash
but i’ll take a look at fix
were going to be doing minor releases with minor fixes only occasionally as they build up from now on so idk when itll be available
