### ISSUE TITLE
Can't Interact With Anything

### ISSUE THREAD

**Issue by Captain238120** [amblelabs/ait#308]
TARDIS interior cannot be interacted with at all (can't place/break blocks, console has no hitboxes, etc.) 

Steps to reproduce the behavior I am experiencing:
1. Go to a world of yours you made in 1.20.1 BEFORE you downloaded the mod.
2. Spawn/create a TARDIS.
3. Go inside.
4. See that you cannot break/place blocks. It is almost as if you are in adventure mode, but the TARDIS console also has no proper controls.

AIT Version:
ait-1.0.4-1.20.1-release

NOTE: 
Any new world made with the mod installed does not cause this issue. Only worlds made before you downloaded the AIT mod do this.

I know I could just make a new world and boom, problem solved, but I am trying to keep this world for a reason and would really appreciate it if someone could find a solution to this bug!

**Comment by DrTheodor** [comment]
That's a very interesting issue. Do you happen to have the logs?

**Comment by Captain238120** [comment]
> That's a very interesting issue. Do you happen to have the logs?

While I do not have any logs for this, I have done some digging and found some unique issues that may be connected to this one.

For example, when you create your TARDIS, all that data for the TARDIS goes into the world folder under "ait". Most of the data from a TARDIS made in a new world (post mod download) and an old world (pre mod download) are the same except for two things:

1. The TARDIS from the old world is missing 20 lines of data (185 instead of 205 like the new one)
2. The TARDIS from the old world is missing console information

Here is the new world TARDIS console info (starting from the uuid & ending at TARDIS ID): 

 "uuid": "2dee1097-ae5b-4a21-ae70-0149060904bf",
  "desktop": {
    "schema": "ait:type_40",
    "doorPos": {
      "direction": "NORTH",
      "dimension": "ait:tardis_dimension",
      "field_11175": 42013,
      "field_11174": 1,
      "field_11173": 87139
    },
    "consoles": [
      {
        "uuid": "01598733-951c-479c-9d84-bb2674f9191d",
        "position": {
          "dimension": "ait:tardis_dimension",
          "field_11175": 42013,
          "field_11174": 1,
          "field_11173": 87123
        },
        "tardisId": "2dee1097-ae5b-4a21-ae70-0149060904bf",
        "id": "console"
      }
    ],
    "corners": {
      "first": {
        "field_11175": 41875,
        "field_11174": 0,
        "field_11173": 86984
      },
      "second": {
        "field_11175": 42131,
        "field_11174": 0,
        "field_11173": 87240
      }
    },
    "tardisId": "2dee1097-ae5b-4a21-ae70-0149060904bf",

Now, here is the TARDIS made in the old world (also starting from uuid and ending with TARDIS ID):

 "uuid": "7ab5215b-e917-4a5b-88d1-5dced953f82b",
  "desktop": {
    "schema": "ait:type_40",
    "doorPos": {
      "direction": "NORTH",
      "dimension": "ait:tardis_dimension",
      "field_11175": 93037,
      "field_11174": 1,
      "field_11173": 57204
    },
    "corners": {
      "first": {
        "field_11175": 92899,
        "field_11174": 0,
        "field_11173": 57049
      },
      "second": {
        "field_11175": 93155,
        "field_11174": 0,
        "field_11173": 57305
      }
    },
    "tardisId": "7ab5215b-e917-4a5b-88d1-5dced953f82b",

I have provided both TARDIS files from the new world (post mod download) and old world (pre mod download) down below:

[2dee1097-ae5b-4a21-ae70-0149060904bf (new world).json](https://github.com/Loqor/ait/files/15340084/2dee1097-ae5b-4a21-ae70-0149060904bf.new.world.json)
[7ab5215b-e917-4a5b-88d1-5dced953f82b (old world).json](https://github.com/Loqor/ait/files/15340085/7ab5215b-e917-4a5b-88d1-5dced953f82b.old.world.json)

**Comment by Duzos** [comment]
and you placed down a console in the world that’s broken?
my bet is because verification was removed (but it was bad anyway so fair)

**Comment by Captain238120** [comment]
> and you placed down a console in the world that’s broken? my bet is because verification was removed (but it was bad anyway so fair)

Yea, the crazy thing is that it says that there is no console, but when you create the TARDIS, not only does it generate an interior (that you can't break any blocks or place any blocks (including a new console)), it also spawns the Type 40 console like normal. You can even middle mouse button it and it will give you the console item. However, none of the buttons work. I don't really know how else to describe it, so I would suggest (if you want to see this problem for yourself) uninstalling the mod, creating a world without the mod, reinstall the mod and see if this issue happens to you.

**Comment by Duzos** [comment]
what does it say in logs like when youre doing this?
what are you using to launch the game

**Comment by Loqor** [comment]
This is a known bug. I fixed this recently in our development environment.
What happens is when you load a world with no tardises, and then install the mod and put down a tardis, the required stuff that gets generated on world gen isn't generated, so it just.. doesn't have a TARDIS. The file doesn't get generated, etc.
Anyway, it also causes memory leaks if you go to another world *WITH* TARDISes and then back into one that doesn't and then back into the one that had them, causing the files to delete and the console to spam "cannot find TARDIS with id <tardis_id>".
I fixed this with one of two things:
- First, I made sure the reset is placed *after* the saving of the TARDIS file .json's, which is the original problem causing this in the first place, is the CTM/STM (Tardis Managers) not being loaded, therefore, the list is null and can't be added to.
- Secondly, I also made sure it reset the CTM list when you disconnect from a world, wiping the CTM of that world so it doesn't carry over.

Suffice to say, this bug is fixed in the next update.

**Comment by Captain238120** [comment]
Hey, so 5 days have passed and (once again) this issue still persists. I even made a new world AFTER having the mod installed, and the TARDIS still won't let me interact with anything, break anything or build anything. I checked the info on the TARDIS in the .ait folder, and this time, strangely, everything is there. All 205 lines of it. So I'm starting to think that this isn't just a "world was generated before TARDIS was in it" kind of bug. This is something else.

**Comment by DrTheodor** [comment]
The issue should be fixed with the next update. >.>
We may or may not release a hotfix version with the fixes ported from the upstream depending on how much stuff is left to add/fix/change.

**Comment by Captain238120** [comment]
I mean, the weird thing is that it works on my super flat testing world (though it is not creating a .ait folder which is also strange). I'm just curious if there is anything I can do in the meantime to potentially fix this issue while both myself and the rest of the people on my server wait for the next release/hotfix, you know?
